// protocol/x402/client.ts
//
// x402 v2 buyer-side client. Wraps native fetch so that any request which
// returns HTTP 402 is automatically retried with a signed PAYMENT-SIGNATURE
// header generated by the configured EVM scheme (viem account).
//
// Reference: https://github.com/x402-foundation/x402  (@x402/fetch v2.10)

import {
  wrapFetchWithPaymentFromConfig,
  decodePaymentResponseHeader,
} from '@x402/fetch';
import { ExactEvmScheme } from '@x402/evm/exact/client';
import { privateKeyToAccount } from 'viem/accounts';
import type { Hex } from 'viem';

const FACILITATOR_URL =
  process.env.X402_FACILITATOR_URL || 'https://www.x402.org/facilitator';

export interface X402ClientOptions {
  /** 0x-prefixed EVM private key. */
  privateKey: string;
  /**
   * CAIP-2 network identifier(s) the client may pay on. Use "eip155:*"
   * for any EVM chain, or e.g. "eip155:84532" for Base Sepolia.
   */
  network?: string;
}

export class X402Client {
  private fetchWithPayment: typeof fetch;
  readonly account: ReturnType<typeof privateKeyToAccount>;

  constructor(opts: X402ClientOptions) {
    const pk = (opts.privateKey.startsWith('0x')
      ? opts.privateKey
      : `0x${opts.privateKey}`) as Hex;
    this.account = privateKeyToAccount(pk);

    this.fetchWithPayment = wrapFetchWithPaymentFromConfig(fetch, {
      schemes: [
        {
          network: (opts.network ?? 'eip155:*') as `${string}:${string}`,
          client: new ExactEvmScheme(this.account),
        },
      ],
    });
  }

  /**
   * Make an HTTP request that automatically resolves 402 challenges via
   * the configured payment scheme.
   */
  async fetch(url: string, init?: RequestInit): Promise<Response> {
    return this.fetchWithPayment(url, init);
  }

  /**
   * Decode the PAYMENT-RESPONSE settlement header (returned by the resource
   * server after the facilitator settles on-chain).
   */
  decodeSettlement(response: Response) {
    const header = response.headers.get('PAYMENT-RESPONSE');
    if (!header) return null;
    return decodePaymentResponseHeader(header);
  }
}

export async function verifyX402ClientSetup(privateKey: string): Promise<boolean> {
  const client = new X402Client({ privateKey });
  console.log(`[x402] Buyer wallet: ${client.account.address}`);
  console.log(`[x402] Facilitator: ${FACILITATOR_URL}`);
  return true;
}
