import { Navbar } from '@/components/Navbar';
import { ArrowRight, TrendingUp, Coins, Gift } from 'lucide-react';
import Link from 'next/link';

export default function RewardsPage() {
  return (
    <main className="flex flex-col bg-[#F5F5F5] min-h-screen">
      <Navbar />
      
      <section className="px-6 pt-40 pb-16 max-w-[88rem] mx-auto w-full text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 text-emerald-600 font-medium text-sm mb-8">
          <TrendingUp className="w-4 h-4" /> Current Base APY: 12.4%
        </div>
        <h1 className="text-black text-6xl md:text-7xl font-medium leading-tight mb-6 max-w-4xl mx-auto" style={{ letterSpacing: '-0.04em' }}>
          Make your liquidity work for you.
        </h1>
        <p className="text-black/60 text-xl leading-relaxed mb-10 max-w-2xl mx-auto">
          Supply fiat or crypto to the Beanstick Network and let autonomous agents route your capital to facilitate trades, earning you passive fees on every settlement.
        </p>
      </section>

      <section className="px-6 pb-24 max-w-[88rem] mx-auto w-full">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-white rounded-3xl p-10 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-black/5">
            <div className="w-14 h-14 bg-[#F9F9F9] rounded-full flex items-center justify-center mb-6">
              <Coins className="w-7 h-7 text-black" />
            </div>
            <h2 className="text-3xl font-medium mb-4">Run an LP Agent</h2>
            <p className="text-black/60 text-lg mb-8 leading-relaxed">
              Deploy a lightweight node that connects to your bank account and crypto wallet. The agent automatically fulfills P2P requests and collects spread fees on your behalf.
            </p>
            <Link href="#" className="inline-flex items-center gap-2 text-black font-medium hover:opacity-70 transition-opacity">
              View setup guide <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          <div className="bg-white rounded-3xl p-10 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-black/5">
            <div className="w-14 h-14 bg-[#F9F9F9] rounded-full flex items-center justify-center mb-6">
              <Gift className="w-7 h-7 text-black" />
            </div>
            <h2 className="text-3xl font-medium mb-4">Staking Rewards</h2>
            <p className="text-black/60 text-lg mb-8 leading-relaxed">
              Not ready to run an agent? Stake your assets directly into the public liquidity pools and earn a baseline yield generated by the active swarm.
            </p>
            <Link href="#" className="inline-flex items-center gap-2 text-black font-medium hover:opacity-70 transition-opacity">
              Launch staking dashboard <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
